[package]
name = "avalanche-telemetry-cloudwatch"
version = "0.0.28" # https://github.com/ava-labs/avalanche-telemetry/releases
edition = "2021"
rust-version = "1.66"
description = "Avalanche telemetry agent"
repository = "https://github.com/ava-labs/avalanche-telemetry"
readme = "README.md"
license = "Apache-2.0"

[[bin]]
name = "avalanche-telemetry-cloudwatch"
path = "src/main.rs"

[dependencies]
aws-manager = "0.22.4" # https://crates.io/crates/aws-manager/versions
aws-sdk-cloudwatch = "0.22.0"
aws-sdk-ec2 = "0.22.0"
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
command-manager = "0.0.1"
env_logger = "0.10.0"
http-manager = "0.0.6"
log = "0.4.17"
prometheus-manager = "0.0.20"
random-manager = "0.0.2"
tokio = { version = "1.23.0", features = ["full"] }
