[package]
name = "avalanche-telemetry-cloudwatch"
version = "0.0.54" # https://github.com/ava-labs/avalanche-telemetry/releases
edition = "2021"
rust-version = "1.67"
description = "Avalanche telemetry agent"
repository = "https://github.com/ava-labs/avalanche-telemetry"
readme = "README.md"
license = "Apache-2.0"

[[bin]]
name = "avalanche-telemetry-cloudwatch"
path = "src/main.rs"

[dependencies]
aws-manager = { version = "0.24.8", features = ["cloudwatch", "ec2"] } # https://crates.io/crates/aws-manager
aws-sdk-cloudwatch = "0.24.0"
chrono = "0.4.23"
clap = { version = "4.1.4", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
env_logger = "0.10.0"
http-manager = "0.0.12"
log = "0.4.17"
prometheus-manager = "0.0.22"
tokio = { version = "1.25.0", features = ["full"] }
