[package]
name = "avalanche-telemetry-cloudwatch"
version = "0.0.11"
edition = "2021"
rust-version = "1.64"
readme = "README.md"
license = "Apache-2.0"

[[bin]]
name = "avalanche-telemetry-cloudwatch"
path = "src/main.rs"

[dependencies]
aws-manager = "0.19.0" # https://crates.io/crates/aws-manager/versions
aws-sdk-cloudwatch = "0.19.0"
aws-sdk-ec2 = "0.19.0"
chrono = "0.4.22"
clap = { version = "4.0.2", features = ["cargo", "derive"] }
command-manager = "0.0.1"
env_logger = "0.9.1"
http-manager = "0.0.3"
log = "0.4.17"
prometheus-manager = "0.0.13"
random-manager = "0.0.1"
tokio = { version = "1.21.2", features = ["full"] }
