[package]
name = "avalanche-telemetry-cloudwatch"
version = "0.0.37" # https://github.com/ava-labs/avalanche-telemetry/releases
edition = "2021"
rust-version = "1.66"
description = "Avalanche telemetry agent"
repository = "https://github.com/ava-labs/avalanche-telemetry"
readme = "README.md"
license = "Apache-2.0"

[[bin]]
name = "avalanche-telemetry-cloudwatch"
path = "src/main.rs"

[dependencies]
aws-manager = { version = "0.22.20", features = ["cloudwatch", "ec2"] } # https://crates.io/crates/aws-manager
aws-sdk-cloudwatch = "0.22.0"
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
env_logger = "0.10.0"
http-manager = "0.0.6"
log = "0.4.17"
prometheus-manager = "0.0.21"
tokio = { version = "1.24.1", features = ["full"] }
